### PR TITLE
Fix the broken triangle generation

### LINKED ISSUE #353: Tesselation is broken
Filing a new bug to act as a little notepad for myself.

The following object has a huge erroneous spike when rendered with resolution=2:

```haskell
translate (V3 0.0 (-27.5) 0.0) (union [translate (V3 62.0 0.0 33.0) (union [translate (V3 (-124.0) 0.0 0.0) (cubeR 0.0 False (V3 124.0 124.0 2.0)),translate (V3 (-56.0) 62.0 (-33.0)) (union [translate (V3 0.0 0.0 35.0) (union [translate (V3 0.0 0.0 (-17.5)) (difference (translate (V3 0.0 0.0 (-17.5)) (cylinder 42.0 35.0)) [translate (V3 0.0 0.0 (-15.5)) (cylinder 40.0 33.0)]),union [translate (V3 0.0 0.0 (-2.0)) (cylinder 48.0 2.0),emptySpace]]),emptySpace])]),translate (V3 (-3.5) (-50.0) 0.0) (union [translate (V3 0.0 (-9.5) 0.0) (union [translate (V3 0.0 0.0 8.5) (rotate3 (3.141592653589793,0.0,0.0) (translate (V3 (-62.0) (-9.5) (-8.5)) (cubeR 0.0 False (V3 124.0 19.0 17.0)))),union [translate (V3 61.0 0.0 0.0) (union [translate (V3 0.0 (-4.0) 0.0) (cubeR 0.0 False (V3 8.0 8.0 2.0)),translate (V3 (-2.0) (-4.0) 0.0) (cubeR 0.0 False (V3 2.0 8.0 8.0))]),emptySpace]]),translate (V3 0.0 52.0 0.0) (union [translate (V3 (-52.0) (-54.0) 0.0) (cubeR 0.0 False (V3 104.0 54.0 17.0)),translate (V3 0.0 (-2.0) 0.0) (difference (extrudeR 0.0 (polygonR 0.0 [V2 (-48.0) 0.0,V2 48.0 0.0,V2 0.0 60.0]) 17.0) [translate (V3 0.0 0.0 2.0) (extrudeR 0.0 (polygonR 0.0 [V2 (-46.0) 0.0,V2 46.0 0.0,V2 0.0 58.0]) 13.0)])])])])
```

2020-12-15-000535_565x310_scrot

### PR DESCRIPTION
**Pull request by isovector**
This fixes the broken triangles. Detailing was attempting to do... something... and it didn't work.

All of the changed golden tests pass my eyeball test.

Fixes #353

### CODE REVIEW

**Comment by isovector** [comment]
This doesn't fix it, it just makes the broken triangles less bad. When trying to reproduce #280, I stumbled across this:

```
writeSTL 3 "/tmp/yo.stl"  $ implicit (\(V3 x y z) -> x^4 + y^4 + z^4
 - 15000) (pure (-20),pure 20) <> (translate (pure 20) $ cubeR 0 True (pure 15)) 
```

which before this patch looks like this:

2020-12-16-135014_598x260_scrot

and after:

2020-12-16-135038_512x250_scrot

notice there are still whiskers on the corner.

**Comment by isovector** [comment]
Commenting out this:

https://github.com/colah/ImplicitCAD/blob/fcf5d34804da2fe531b8f51507c2587e3b0edcc1/Graphics/Implicit/Export/Render/RefineSegs.hs#L56-L65

completely removes the whiskers

File: Graphics/Implicit/Export/Render/RefineSegs.hs [hunk 1]
```diff
@@ -47,23 +47,7 @@ detail n res obj (Polyline [p1, p2]) | n < 2 =
...
-                 let
-                   (dX, dY) = (- derivX*midval/derivNormSq, - derivY*midval/derivNormSq)
-                   mid' = mid + V2 dX dY
-                   midval' = obj mid'
-                   posRatio = midval/(midval - midval')
-                   mid'' = mid + V2 (dX*posRatio) (dY*posRatio)
-                 in
-                   addPolylines (detail (n+1) res obj (Polyline [p1, mid''])) (detail (n+1) res obj ( Polyline [mid'', p2] ))
-               else Polyline [p1, p2]
+           else Polyline [p1, p2]
```
Comment (julialongtin) [inline Graphics/Implicit/Export/Render/RefineSegs.hs:50]:
```suggestion
           -- NOTE: we used to have a routine for increasing the sharpness of corners here, but it was too buggy. - JEL
           else Polyline [p1, p2]
```
