### PR TITLE
Fix monoid instances; add tests of algebraic properties for symbolic objects

### LINKED ISSUE #323: Monoid instance is FUBAR
There are no primitives that work as `mempty`. `cube 0` still tracks distance from the origin, and `union []`'s implicit is equal to `0` everywhere.

### PR DESCRIPTION
**Pull request by isovector**
This PR:

1. Primarily, fixes #323, via:
2. Adding two new primitives to `Object`: `emptySpace` and `fullSpace`. The former acts as a proper unit for union, and the latter is its corresponding dual (and also annihilator for union)
3. Enforces associativity of the `(<>)` operation by fiat. The underlying bug in `union` is still present, but `(<>)` correctly reassociates everything so it Just Works
4. Adds tests to prove that the monoid instances are lawful
5. Adds thousands(!) of other tests, proving tons of algebraic properties about symbolic objects.

### CODE REVIEW

File: Graphics/Implicit/Primitives.hs [hunk 1]
```diff
@@ -259,19 +262,23 @@ instance Object SymbolicObj2 ℝ2 where
     implicit a b= EmbedBoxedObj2 (a,b)
 
 instance Object SymbolicObj3 ℝ3 where
```
Comment (cartazio) [inline Graphics/Implicit/Primitives.hs:264]: one thing i was wondering about when looking at the code yesterday is: is there a good reason the Object class isn't exported?

Comment (isovector) [reply Graphics/Implicit/Primitives.hs:264]: Not AFAIK. To hide `getImplicit` is my guess?

Comment (isovector) [reply Graphics/Implicit/Primitives.hs:264]: PS we're hanging out in #ImplicitCAD on freenode. It's a better place to ask the maintainer things :)

**Comment by cartazio** [comment]
But that could be accomplished by splitting it off into a parent or child
class OR not including that method in the class exports?

I guess another option for making object polymorphism possible in user
space is export a type synonym alias for Object that can be used by client
code? Makes it nameable again but avoids allowing new client instances?

File: Graphics/Implicit/Primitives.hs (hunk 1 above)
Comment (isovector) [reply Graphics/Implicit/Primitives.hs:264]: PPS: It is exported as of last week: https://github.com/colah/ImplicitCAD/blob/master/Graphics/Implicit.hs#L19. There just hasn't been a release since then!

File: tests/Graphics/Implicit/Test/Instances.hs [hunk 2]
```diff
@@ -235,7 +235,7 @@ isValid3 (CubeR _ (x0, y0, z0)) = (0 < x0) && (0 < y0) && (0 < z0)
 isValid3 (Cylinder _ r h) = r > 0 && h > 0
 isValid3 s =  -- Otherwise, make sure it has > 0 volume
   let (dx, dy, dz) = boxSize s
-   in notElem 0 [dx, dy, dz]
+   in all (> 0) [dx, dy, dz]
```
Comment (cartazio) [inline tests/Graphics/Implicit/Test/Instances.hs:238]: pedantic note, should stuff thats ~ 1 ULP or so in every dim be legal??

File: Graphics/Implicit/ObjectUtil/GetBox3.hs [hunk 3]
```diff
@@ -41,18 +41,20 @@ outsetBox :: ℝ -> Box3 -> Box3
 outsetBox r (a,b) =
     (a ^-^ (r,r,r), b ^+^ (r,r,r))
 
+infty :: Fractional t => t
```
Comment (julialongtin) [inline Graphics/Implicit/ObjectUtil/GetBox3.hs:44]: why is this needed)

File: Graphics/Implicit/ObjectUtil/GetImplicit3.hs [hunk 4]
```diff
@@ -25,9 +25,14 @@ import Data.VectorSpace (AdditiveGroup((^-^)))
 
 default (ℝ)
 
+infty :: Fractional t => t
```
Comment (julialongtin) [inline Graphics/Implicit/ObjectUtil/GetImplicit3.hs:28]: why is this needed

File: tests/ImplicitSpec.hs [hunk 5]
```diff
@@ -67,6 +72,35 @@ spec = do
           getQuantizedBox . rotate3V (2 * pi - rads) vec . rotate3V rads vec
             =~= getQuantizedBox
 
+  monoidSpec
+
+monoidSpec :: Spec
```
Comment (julialongtin) [inline tests/ImplicitSpec.hs:77]: what is this spec testing for?

**Review by julialongtin — APPROVED** [review]

File: tests/Graphics/Implicit/Test/Instances.hs (hunk 2 above)
Comment (isovector) [reply tests/Graphics/Implicit/Test/Instances.hs:222]: what's a ULP?

Comment (cartazio) [reply tests/Graphics/Implicit/Test/Instances.hs:222]: "unit of least precision". though wikipedia has an equivalent but slightly different acronym https://en.wikipedia.org/wiki/Unit_in_the_last_place 

i probably mean "epsilon, the smallest normalized nonzero positive floating point"

Comment (isovector) [reply tests/Graphics/Implicit/Test/Instances.hs:235]: Tests pass, so I'm OK with it :)

**Comment by isovector** [comment]
The following object still crashes:

```haskell
  DifferenceR3 0.0 (Translate3 (6.000000000000007,-0.0,-44.5) (UnionR3 0.0 [Translate3 (-17.000000000000007,0.0,0.0) (Translate3 (0.0,0.0,38.0) (Rotate3 (Quaternion 0.7071067811865476 (V3 0.0 0.7071067811865475 0.0)) (Translate3 (3.0,-0.0,-17.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) (IntersectR3 0.0 [Shell3 2.0 (Outset3 5.0 (Cylinder 28.0 35.0 35.0)),Cylinder 28.0 50.0 50.0,Translate3 (11.0,0.0,0.0) (Translate3 (-50.0,0.0,0.0) (Translate3 (0.0,0.0,14.0) (Translate3 (-50.0,-50.0,-14.0) (CubeR 0.0 (100.0,100.0,28.0)))))]),Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,17.0) (Translate3 (-0.0,-0.0,11.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) Empty3,Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,-28.0) Empty3)])))])))),Translate3 (-2.0,0.0,0.0) (Translate3 (12.0,0.0,0.0) (Translate3 (0.0,0.0,24.0) (Translate3 (0.0,0.0,-0.0) (UnionR3 0.0 [Translate3 (0.0,0.0,32.5) (Translate3 (-9.5,-11.0,-32.5) Empty3),IntersectR3 0.0 [Translate3 (0.0,0.0,31.5) (Shell3 2.0 (Scale3 (1.1578947368421053,1.1363636363636365,1.0307692307692307) (Translate3 (-9.5,-11.0,-32.5) (CubeR 0.0 (19.0,22.0,65.0))))),Translate3 (-12.0,-13.500000000000002, 0.0) (CubeR 0.0 (24.0,27.000000000000004,2.0))]]))))])) [Translate3 (6.000000000000007,-0.0,-44.5) (UnionR3 0.0 [Translate3 (-17.000000000000007,0.0,0.0) (Translate3 (0.0,0.0,38.0) (Rotate3 (Quaternion 0.7071067811865476 (V3 0.0 0.7071067811865475 0.0)) (Translate3 (3.0,-0.0,-17.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) Empty3,Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,17.0) (Translate3 (-0.0,-0.0,11.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) (Cylinder 6.0 3.0 3.0),Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,-28.0) (Cylinder 28.0 35.0 35.0))])))])))),Translate3 (-2.0,0.0,0.0) (Translate3 (12.0,0.0,0.0) (Translate3 (0.0,0.0,24.0) (Translate3 (0.0,0.0,-0.0) (Translate3 (0.0,0.0,32.5) (Translate3 (-9.5,-11.0,-32.5) (CubeR 0.0 (19.0,22.0,65.0)))))))])]
```

with the error `*** Exception: Prelude.minimum: empty list`.

However, eliminating the `Empty3` constructors makes it successfully `writeSTL`:

```haskell

DifferenceR3 0.0 (Translate3 (6.000000000000007,-0.0,-44.5) (UnionR3 0.0 [Translate3 (-17.000000000000007,0.0,0.0) (Translate3 (0.0,0.0,38.0) (Rotate3 (Quaternion 0.7071067811865476 (V3 0.0 0.7071067811865475 0.0)) (Translate3 (3.0,-0.0,-17.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) (IntersectR3 0.0 [Shell3 2.0 (Outset3 5.0 (Cylinder 28.0 35.0 35.0)),Cylinder 28.0 50.0 50.0,Translate3 (11.0,0.0,0.0) (Translate3 (-50.0,0.0,0.0) (Translate3 (0.0,0.0,14.0) (Translate3 (-50.0,-50.0,-14.0) (CubeR 0.0 (100.0,100.0,28.0)))))])])))),Translate3 (-2.0,0.0,0.0) (Translate3 (12.0,0.0,0.0) (Translate3 (0.0,0.0,24.0) (Translate3 (0.0,0.0,-0.0) (UnionR3 0.0 [IntersectR3 0.0 [Translate3 (0.0,0.0,31.5) (Shell3 2.0 (Scale3 (1.1578947368421053,1.1363636363636365,1.0307692307692307) (Translate3 (-9.5,-11.0,-32.5) (CubeR 0.0 (19.0,22.0,65.0))))),Translate3 (-12.0,-13.500000000000002,0.0) (CubeR 0.0 (24.0,27.000000000000004,2.0))]]))))])) [Translate3 (6.000000000000007,-0.0,-44.5) (UnionR3 0.0 [Translate3 (-17.000000000000007,0.0,0.0) (Translate3 (0.0,0.0,38.0) (Rotate3 (Quaternion 0.7071067811865476 (V3 0.0 0.7071067811865475 0.0)) (Translate3 (3.0,-0.0,-17.0) (UnionR3 0.0 [Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,17.0) (Translate3 (-0.0,-0.0,11.0) (UnionR3 0.0 [Translate3 (0.0,0.0,-0.0) (Cylinder 6.0 3.0 3.0),Translate3 (0.0,0.0,0.0) (Translate3 (0.0,0.0,-28.0) (Cylinder 28.0 35.0 35.0))])))])))),Translate3 (-2.0,0.0,0.0) (Translate3 (12.0,0.0,0.0) (Translate3 (0.0,0.0,24.0) (Translate3 (0.0,0.0,-0.0) (Translate3 (0.0,0.0,32.5) (Translate3 (-9.5,-11.0,-32.5) (CubeR 0.0 (19.0,22.0,65.0)))))))])] 
```

File: tests/ImplicitSpec.hs [hunk 6]
```diff
@@ -1,73 +1,262 @@
...
+
+  failingProp "rotate" $ \rads1 rads2 ->
+    rotate rads2 . rotate rads2
+      =~= rotate (rads1 + rads2)
+
+  prop "full idepotent wrt rotate" $ \rads ->
+    rotate rads fullSpace
+      =~= fullSpace
+
+  prop "empty idepotent wrt rotate" $ \rads ->
```
Comment (sorki) [inline tests/ImplicitSpec.hs:163]: Nitpick typo `idepotent`, prop above as well.

**Comment by isovector** [comment]
Regarding that example that explodes, I think it's caused by getBox3 and is fixed by #319.

File: tests/ImplicitSpec.hs (hunk 6 above)
Comment (isovector) [reply tests/ImplicitSpec.hs:163]: Thanks. Keen eyes!

**Review by julialongtin — APPROVED** [review]
