### PR TITLE
2d shape fixes

### LINKED ISSUE #328: Different implementation for difference between 2D and 3D
The relevant change is 3e15a5e4, which doesn't make the corresponding change in https://github.com/colah/ImplicitCAD/blob/eb10f1b384c4a3b2147027a27a62e88a1f890358/Graphics/Implicit/ObjectUtil/GetImplicit2.hs#L61.

### LINKED ISSUE #334: getImplicit for polygon crashes for an empty list

### LINKED ISSUE #335: getImplicit for polygon produces NaN when two consecutive points are in the list
`getImplicit (polygonR 0 [0, 0, 0]) 0` is `NaN` :imp:

### PR DESCRIPTION
**Pull request by isovector**
This PR:

* ports the changes made in 3e15a5e44d8ff761ff68f366c66e8702c02be913 to also happen in 2D; fixes #328.
* fixes two issues with `getImplicit . polygon`:
    * when given two equal points in a row, it used to produce `NaN`; fixes #335
    * when given zero points, it would crash with a `minimum: empty list`; fixes #334 
* these fixes allow us to reenable the `"difference is complement"` test for 2D

Additionally, it:

* cleans up the generator and shrinkers for 2d polygons
* fixes a missed specialization I accidentally introduced in #324 
* removes `epsilon`, which I forgot to delete in #326

### CODE REVIEW

File: Graphics/Implicit/ObjectUtil/GetImplicit2.hs [hunk 1]
```diff
@@ -1,17 +1,35 @@
...
+import Graphics.Implicit.MathUtil (rmax, infty, reflect, rminimum, rmaximum, distFromLineSeg)
 
 import Data.VectorSpace ((^-^))
-import Data.List (nub, genericIndex, genericLength)
+import Data.List (nub)
+
+
+------------------------------------------------------------------------------
+-- | Filter out equal consecutive elements in the list. This function will
+-- additionally trim the last  element of the lst if it's equal to the first.
```
Comment (julialongtin) [inline Graphics/Implicit/ObjectUtil/GetImplicit2.hs:20]:
```suggestion
-- additionally trim the last element of the list if it's equal to the first.
```

**Review by julialongtin — APPROVED** [review]
